### ISSUE TITLE
"The project begins in:" isn't clear its a year

### ISSUE THREAD

**Issue by euphbriggs** [AnthonyLzq/typescript-project-generator#2]
Thanks for putting this project together. It's handy for someone like me who is coming from outside the Node ecosystem to start a project without having to make all the initial decisions.

I went to generate a project and was confused about the correct input for the "Ths project begins in:" prompt. My first instinct was the value later provided in the "Main file" prompt. I looked at the source code to see it's supposed to be a year, which makes sense now that I know what it should be.

May I recommend either showing its for the copywrite year or having a default value of the current year for an example?

**Comment by AnthonyLzq** [comment]
Thanks for the advice, I will implement that as soon as possible.

**Comment by AnthonyLzq** [comment]
Please, check [`v 1.5.0`](https://github.com/AnthonyLzq/typescript-project-generator/commit/d85d227f74f629b595c86d193db48a5ed7717913).
