### ISSUE TITLE
"'touch' is not recognized as an internal or external command" in Windows

### ISSUE THREAD

**Issue by euphbriggs** [AnthonyLzq/typescript-project-generator#3]
I tried generating a project in Windows today and got this error message:

```
Initializing the process of installation...
Error: Command failed: touch .env
'touch' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'touch .env',
  stdout: '',
  stderr: "'touch' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n'
}
```

If you're open to it, I'd be happy to submit a PR with a cross-platform fix.

**Comment by AnthonyLzq** [comment]
Hey there! I'd appreciate if you can do do that, please, go ahead.

**Comment by AnthonyLzq** [comment]
Hey! Check this out: [`v 1.6.0'`](https://github.com/AnthonyLzq/typescript-project-generator/commit/b21ec529c02358d1aa5fe8ce28a25922b620ddd3).

It is pending to merge with the master branch.

**Comment by AnthonyLzq** [comment]
Well, I've implemented a few changes in the project, after the test I made I think everything is ok. So, please, take a look to the new version: [''v 1.7.0`](https://github.com/AnthonyLzq/typescript-project-generator/commit/4c5643f1bbd54991620134b0340b58e6f380be37).

To summary, support for `windows` users has been added.

**Comment by euphbriggs** [comment]
Excellent, thank you very much! I was planning on working on this sometime this weekend, but you beat me to it. Have a great day!
