### ISSUE TITLE
Email regex is overly strict

### ISSUE THREAD

**Issue by Keating950** [AnthonyLzq/typescript-project-generator#8]
In particular, it will reject anything with a period to the left of the at sign:

    > Email: keating.reid@protonmail.com
    That is not a valid email!

**Comment by AnthonyLzq** [comment]
I will take a look at that.

**Comment by AnthonyLzq** [comment]
It should be fixed with the new version [2.6.0](https://github.com/AnthonyLzq/typescript-project-generator/tree/938a9cff38da9be5177e4df848b032de9d3846dd). I tested the generator with the email you provided me, it worked. I'm closing this until a new bug is found. Thank for your report.
